initial fix for issue 134
saucelabs/node-saucelabs pull request #135
Opened 2022-01-07 13:29 UTC by wswebcreation

This is the initial work to fix https://github.com/saucelabs/node-saucelabs/issues/134

- I've forked binWrapper and "cleaned" from most of the used deps
- removed file and version check. We use SC and the provided version / retrieved latest version should automatically pull the correct one, so IMHO a version check should not be needed

TODO:
- fix unit tests (I couldn't get `index.test.js` working, mocking of the binWrapper failed)

2022-01-07 19:14 UTC, boneskull requested changes
many of my comments here are just suggestions, but I think this is needed:

1. remove `os-filter-obj`
2. add license/copyright from `bin-wrapper`. this can be embedded in the source file

2022-01-07 19:14 UTC, boneskull commented on src/binWrapper.js
> +		}
just golfing, but

```suggestion
		return [...acc, ...Array.isArray(elem) ? item : [item]];
```

are we sure the arrays only potentially go 2 levels deep?  we'd never have `[ [ [ 1, 2, 3 ] ] ]`, right?

2022-01-07 19:14 UTC, boneskull commented on src/binWrapper.js
> +		const files = osFilterObj(this.src() || [])
as mentioned somewhere else, we should just hand-roll this as well.  I'd probably change it so that if the return value would be empty, the exception would be thrown in that function instead of on L113.

2022-01-07 19:14 UTC, boneskull commented on src/binWrapper.js
> +export default class BinWrapper {
in general, this class is still too complicated for what we need.  it'll work for now, but I'd prefer to whittle it way down.

2022-01-07 19:14 UTC, boneskull commented on src/binWrapper.js
> +		files.forEach(file => urls.push(file.url))
remove L110 and

```suggestion
		const urls = files.map(file => file.url)
```

or just get rid of `urls` entirely and iterate over `files` on L118

2022-01-07 19:18 UTC, boneskull commented
It appears we're not actually testing on Node.js v8, so I don't see how we can claim support.  The babel config targets Node.js v10, which is also EOL'd.  We need to add v10 to the matrix if we hope to support it, and v8 if we want to support that.  if either of them fail, we can safely target v12.

2022-01-07 19:31 UTC, boneskull commented
pulling `bin-wrapper` out wreaks havoc on the tests due to the mocking going on:

1. we should not be mocking BinWrapper any more
2. there's an export named `instances` that we haven't pulled in, and the tests use

2022-01-07 19:39 UTC, boneskull commented
OK, the `instances` thing is just a thing we added for testing; it's not part of `bin-wrapper`

2022-01-07 19:41 UTC, boneskull commented
We will also need to add a mock for the `download` lib, or simply avoid `download` entirely since it's just a wrapper around `got` and `decompress`

2022-01-07 21:09 UTC, boneskull commented
@wswebcreation OK, so basically all I did here was fix the tests (assuming CI passes).  We still need to add attribution/copyright/license info.

2022-01-07 21:15 UTC, boneskull commented
@wswebcreation I'll also give you a chance to make any changes you wish from the review.  Let's shoot to get this out early next wk?

oh, and note: the `.prettierrc` I added is just for my own sanity and only affects how code is formatted in an IDE (in my case, vscode).  I haven't added `prettier` itself to the project

2022-01-08 16:23 UTC, wswebcreation commented on package.json
> +    "os-filter-obj": "^2.0.0",
As you mentioned we keep it for now

2022-01-08 16:24 UTC, wswebcreation commented on src/index.js
>              .use('/bin/' + (process.platform.startsWith('win') ? 'sc.exe' : 'sc'))
Nope, not AFAIK

2022-01-08 16:24 UTC, wswebcreation commented on src/binWrapper.js
> +	}
Agree, this need to be fixed with for example prettier, but yes, in a separate PR =)

2022-01-08 16:40 UTC, wswebcreation commented on src/binWrapper.js
> + * and "simplify" the implementation
You mean SC? Because it's this lib is a collection of Sauce Labs options. Main usage is for using the APIs, Sauce Connect downloading and starting is collateral damage and might not be used by every user. So downloading it by default wouldn't be my suggestion

2022-01-08 16:44 UTC, wswebcreation commented on src/binWrapper.js
> +		}
As long as I'm at Sauce we have this structure for the SC zip files

```
|_bin
| |_sc(.exe)
|_some_other_folder
|_COPYRIGHT.md
|_license.html
```

The change that this changes is not that big, but we might want to be cautious with that, what do you think?

2022-01-08 20:27 UTC, wswebcreation commented
@boneskull 

What do you think of this? If you have completely different ideas then feel free to take over and fix it =)

2022-01-10 19:50 UTC, boneskull approved these changes

2022-01-10 19:51 UTC, boneskull commented
@wswebcreation looks fine to me.  I fixed CI and made a couple other tiny tweaks, but if this passes, let's merge it. 

have you released this package before?

2022-01-10 19:52 UTC, boneskull commented
looks like I didn't fix CI

2022-01-10 20:46 UTC, boneskull commented
lol, coverage threshold :(

2022-01-10 22:49 UTC, boneskull commented
@wswebcreation I added tests for `SauceConnectLoader`.  I'll merge and publish

2022-01-10 22:50 UTC, merged